# Generated by Django 4.2.2 on 2023-06-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lynk", "0002_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="text_body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
