# Generated by Django 4.2.2 on 2023-06-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lynk", "0003_element_text_body_user_bio_alter_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="element",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("text", "Text Element"),
                    ("link", "Website Link"),
                    ("youtube", "Youtube Video"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
