# Generated by Django 4.2.2 on 2023-06-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lynk", "0004_user_password_alter_element_item_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.CharField(
                blank=True,
                default="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
                max_length=1024,
                null=True,
            ),
        ),
    ]
