# Generated by Django 4.2.2 on 2023-06-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lynk", "0006_user_instagram_user_linkedin_user_tiktok_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="element",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("", "Select an Element Type"),
                    ("text", "Text Element"),
                    ("link", "Website Link"),
                    ("youtube", "Youtube Video"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="element",
            name="text_header",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="element",
            name="web_link",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="element",
            name="web_link_header",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="element",
            name="yt_link",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
